version: '3.9'

networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: nginx:stable-alpine
    container_name: dev_nginx
    volumes:
      - ./api/:/var/www/api
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:81"
    networks:
      - laravel

  workspace_php:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: dev_workspace_php
    volumes:
      - ./api:/var/www/api
    ports:
      - "9004:9004"
    networks:
      - laravel

  mysql:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: mysql:5.6
    ports:
      - "3306:3306"
    container_name: dev_mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dev
    networks:
      - laravel

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: phpmyadmin/phpmyadmin:latest
    container_name: dev_phpmyadmin
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    networks:
      - laravel